# Week 2 

In this week's R exercise we are making the regression analysis from the questionare data about students' learning methods (deep and surface learning) and attitudes toward the learning progress and study subject. The answers are scaled and combined together with final exam points, overall attitudes toward statistics, gender and age. Before the analysis, we did data wrangling step (where the data table is converted into different type of file), and in this step the data was already filtered so that those answers that got 0 points are left out from the data table. 

This means that the data table has seven different variables. The first variable is gender, which can be either female or male. The next one is age, and it is answered by integer value, as well as question about attitude. Also the exam points are integers in the table. However, the points coming from questions about learning (surface, strategic, deep) are done in a way that they score numbers which are then averaged into single values. In order to compare these factors, we might need to progress the data more before actual analysis. 


```{r}
# Reading the data into R (students2014) from the  local data wrangling file (learning2014.txt). Setting the header=TRUE because file contains the names of the variables as its first line.

students2014<-read.table("~/Tiedostot_J/IODS-project/data/learning2014.txt", header=TRUE)

#Analysis of the data (structure, dimensions and headings) Explore the structure and the dimensions of the data and describe the dataset briefly, assuming the reader has no previous knowledge of it.
str(students2014)
dim(students2014)
head(students2014)


print(students2014$Attitude)
```
